"""Report Synthesizer — final mutual-fund-oriented investment note."""

from langchain_core.messages import HumanMessage, SystemMessage

from pruinsight.llm import get_llm
from pruinsight.state import AgentState

SYSTEM = """You are the Lead Equity Research Writer at ICICI Prudential AMC (PruInsight).

Synthesize inputs from Market Research, Filings (primary sources), Fundamentals,
Mutual Fund / AMFI context, and Risk into one coherent note for mutual fund
portfolio managers and investment committees.

Rules:
- Balanced, institutional tone. No buy/sell/target-price recommendations.
- Prefer **filing-backed** facts over headlines when they conflict; say so explicitly.
- Use **AMFI / factsheet** context for how stocks sit in fund categories and mandates.
- Distinguish facts, consensus narrative, and internal interpretation.
- Keep it actionable for a MF desk: what to watch, why it matters, what is uncertain.
- Always end with a clear DISCLAIMER.

Structure the final report as:

# PruInsight Note: <title>

## Executive summary
## Market & news context
## Primary sources & filings
## Fundamentals snapshot
## Mutual fund context (AMFI / factsheets)
## Risk view
## Mutual fund perspective (holding horizon, sizing considerations, monitoring)
## Key takeaways
## Disclaimer

Do NOT invent a detailed vendor data-sources appendix — a complete **Data sources**
section is appended automatically after you write the note.
"""

DISCLAIMER = """
---
**Disclaimer:** This note is generated by an AI research assistant (PruInsight) for educational and informational purposes only. It does not constitute investment advice, a recommendation, or an offer to buy or sell any securities or mutual fund schemes. Past performance is not indicative of future results. Data may be delayed or incomplete. Filings and factsheet text may be partial. Readers should conduct independent due diligence and consult licensed advisors. Views are not official positions of ICICI Prudential Asset Management Company Limited.
"""


def synthesizer_node(state: AgentState) -> dict:
    """Merge all agent outputs into a final PruInsight report."""
    llm = get_llm(temperature=0.2)

    user_msg = f"""Original query: {state['query']}
Symbols: {', '.join(state.get('symbols') or []) or 'N/A'}

=== Market research ===
{state.get('market_research') or 'N/A'}

=== Filings / primary sources ===
{state.get('filings_context') or 'N/A'}

=== Fundamentals ===
{state.get('fundamentals') or 'N/A'}

=== Mutual fund / AMFI context ===
{state.get('mf_context') or 'N/A'}

=== Risk assessment ===
{state.get('risk_assessment') or 'N/A'}

Write the final PruInsight multi-agent research note.
"""

    messages = [
        SystemMessage(content=SYSTEM),
        HumanMessage(content=user_msg),
    ]
    response = llm.invoke(messages)
    body = response.content or ""
    if "disclaimer" not in body.lower():
        body = body.rstrip() + "\n" + DISCLAIMER

    return {
        "final_report": body,
        "messages": [response],
    }
